### ISSUE TITLE
Vuex support?

### ISSUE THREAD

**Issue by JivanRoquet** [jbaysolutions/vue-grid-layout#325]
**Software version (please complete the following information):**
 - Browser Chrome
 - Vue Version 2.5.7
 - vue-grid-layout Version: 2.3.4

**Describe the bug**
Not technically a bug, but when I use a `<grid-layout>` element with the `layout` property based on an array stored in Vuex, an error is triggered:

> vue.runtime.esm.js?2b0e:1887 Error: [vuex] do not mutate vuex store state outside mutation handlers.

Is there a way to use vue-grid-layout with a Vuex-stored array?

**Comment by bwolfe-celartem** [comment]
This has been gone over a few times in other bugs.  The most complete solutions are in this issue here: https://github.com/jbaysolutions/vue-grid-layout/issues/157

Basically you've got 2 options. Either commit the state back to the store on each action (move/moved/resize/resized/onLayoutUpdate/etc) or clone the layout to a new var on component creation and commit that clone back to the the store when the layout is updated.
