### ISSUE TITLE
Cells aspect ratio

### ISSUE THREAD

**Issue by focussing** [jbaysolutions/vue-grid-layout#342]
I need to create something like this:

![Schermafbeelding 2019-07-16 om 13 51 33](https://user-images.githubusercontent.com/26736152/62362567-89ace800-b51d-11e9-9201-f3833ff46ca9.png)

I use vue-grid-layout which I initialize with the following layout:
```
			layout: [
				{ x: 0, y: 0, w: 2, h: 5, i: 0 },
				{ x: 2, y: 0, w: 2, h: 5, i: 1 },
				{ x: 0, y: 5, w: 4, h: 5, i: 2 },
				{ x: 4, y: 0, w: 4, h: 8, i: 3 },
				{ x: 4, y: 8, w: 4, h: 2, i: 4 },
				{ x: 0, y: 10, w: 2, h: 5, i: 5 },
				{ x: 2, y: 10, w: 4, h: 5, i: 6 },
				{ x: 6, y: 10, w: 2, h: 5, i: 7 }
			]
<grid-layout
    :layout.sync="layout"
    :col-num="8"
    :row-height="30"
    :responsive="false"
    :vertical-compact="true"
    :margin="[25, 25]"
    :use-css-transforms="true"
    :auto-size="false"
    :is-draggable="false"
    :is-resizable="false"
    :is-mirrored="false"
    :static="false"
>
    <grid-item v-for="item in layout" :x="item.x" :y="item.y" :w="item.w" :h="item.h" :i="item.i" :key="item.i">
        <div class="divv text-white">
            <span>
                ({{item.i}})
                <span v-if="item.i==1">
                    Lorem ipsum dolor sit amet,
                    consectetuer adipiscing elit,
                    sed diam nonummy nibh euismod
                    tincidunt’
                </span>
            </span>
        </div>
    </grid-item>
</grid-layout>
```
The result is this; which is quite good.
![Schermafbeelding 2019-08-02 om 12 04 47](https://user-images.githubusercontent.com/26736152/62362672-c1b42b00-b51d-11e9-895a-4efbc177d4b1.png)

The only this is that if the browser window is resized, the width of the cells change.
What can I do to keep the aspect ratio of the cells constant, for example cell "0" square?

**Comment by tornography** [comment]
I don't think this is possible, as the item need a room to snap to. So if the rows have different heights, due to the ratio, calculation of these snap areas is problematic.

Do you really need this to dynamically re-arrange these ratio-items, or do you just use this tool as a layout. If it's just static layout I'd recommend to use css grids, where you can define multiple/different line heights and columns widths.
![image](https://user-images.githubusercontent.com/878616/68394401-0c24f380-016e-11ea-969f-280913b79dd0.png)

**Comment by gmsa** [comment]
I don't think it's possible to keep the aspect ratio
