### ISSUE TITLE
Dynamic component not rendering with responsive grid layout

### ISSUE THREAD

**Issue by gamoridev** [jbaysolutions/vue-grid-layout#418]
**Software version:**
 - Browser Version 81.0.4044.113 (Official Build) (64-bit)
 - Vue Version 2.5.22
 - vue-grid-layout Version: 2.3.7

Hello, everyone. I'm trying to use dynamic components on my grid-item chain. However, when I add the "responsive" property on the grid-layout, my component doesn't render.
It appears on the dom as `<!---->`

Here's the error reproduced [CodeSandbox Example](https://codesandbox.io/s/vue-template-eb445?file=/src/App.vue).

In the first `<grid-layout>`, I've set the property **responsive** to true. And my `<component>` tag doesn't load.
In the second one, the responsive prop is false. Then, my `<component>` tag loads.

**To Reproduce**
1. Go to CodeSandBox example
2. See the error

**Expected behavior**
Dynamic component loads while using responsive grid-layout.

**Comment by charliebdewing** [comment]
It seems like the responsive layout isn't able to deal with the way you asynchronously load in your components in the data.
Perhaps because the 'layout.sync' is overwriting the promise value? Or just the way the responsive layout deals with the 'layout' prop.
The responsive layouts use the function 'cloneLayoutItem' which uses `JSON.parse(JSON.stringify(layoutItem));`. I believe this would remove item.content's dynamic component promise. 
I'm unable to confirm anything right now on this PC.

If you change `:layout.sync=""' to just  `:layout=""' it works with seemingly no issues.

If some issues do arise you could always import your components the normal way or add them to the layout data once the promise has been fulfilled? I understand there are numerous reasons why you may not be able to do this in your system but I only have the context of the example you posted.

Another option is to copy what I've done on this [CodeSandbox Example](https://codesandbox.io/s/vue-template-rdu1s?file=/src/App.vue) and move the item's content out of the layout data into it's own variable. Doing this means the layout coordinate values are kept separate from the content inside the items.

**Comment by gamoridev** [comment]
Thank you for your response, @charliebdewing.

I wasn't working on the project for the last few days and it's because I didn't replied you.
I can't remove the .sync prop while using the `responsive`. If i do this, the slots of the grid-layout (cols and rows) behaves wrongly when the screen size changes.

So I'm using your second solution that keep the layout separated from the content and it's working!
