### ISSUE TITLE
Remove responsive layout

### ISSUE THREAD

**Issue by maisasb** [jbaysolutions/vue-grid-layout#445]
Hi, 
I need some help with the responsive layout.
I set the responsive to false so that the items don't stretch, but they keep stretching at higher resolutions.
I would like the GridItem to be the same width as it was created, regardless of the resolution.
Thank you

**Comment by dehood** [comment]
Wouldn't be easier to apply CSS styling or use something like bootstrap?

**Comment by maisasb** [comment]
Thank you for the answer, but how?
I need to lock some GridItems to not scretch when resolution change.

**Comment by dehood** [comment]
Hi, checkout this if you're using or planning to use Bootsrap 👉🏼  [https://getbootstrap.com/docs/4.5/layout/grid/](https://getbootstrap.com/docs/4.5/layout/grid/) otherwise, you can "lock" pixels using CSS rules.

Just inspect the element > find CSS class > add it to your .css file and override the parameters. Use `!important` if needed.

That's what I would do.

**Comment by maisasb** [comment]
Thank you for your help!
That will solve my problem, I can set specifc class for the elements that I want to lock the size and use css to set max-width for them.

Thank you again!
