### ISSUE TITLE
Is Typescript support planned?

### ISSUE THREAD

**Issue by sokolinivan** [jbaysolutions/vue-grid-layout#636]
This has a big influence on whether the library will be used in the future. At the moment I can't even get Vue3 to run, let alone Typescript.

**Comment by MikesGlitch** [comment]
I currently use it with typescript and vue 3/composition api so it's totally possible.  I had to define my own types though.

**Comment by sokolinivan** [comment]
> I currently use it with typescript and vue 3/composition api so it's totally possible. I had to define my own types though.

Thank you so much for your reply! Are you using your types in any code here posted on GitHub? I'd like to take a look at it.

**Comment by MikesGlitch** [comment]
Yeah tbh I'd really like to contribute to this repository with some examples and updates to the vue3 branch but it seems there are lots of pr's unmerged which is giving me pause.  

@gmsa  Is anyone from jbarysolutions actively maintaining this?  How would I go about contributing to this repo?  There are quite a lot of prs outstanding and unmerged.

I can't give much away since I'm doing this as a part of a work project.  However I've got these:
````
declare module 'vue-grid-layout' {
  import Vue from 'vue'
  import { Widget } from '@/typings/widgets'

  export class GridLayout extends Vue {}

  export class GridItem extends Vue {}

  export interface GridItemData {
    x: number
    y: number
    w: number
    h: number
    i: string
    minH?: number
    minW?: number
    widget: Widget
  }

  export interface GridItemRef extends GridItemData {
    dragging: { top: number; left: number }
    calcXY: (top: number, left: number) => { x: number; y: number }
    calcColWidth: () => number
  }

  interface GridLayoutRef {
    dragEvent: (eventName: string, id: string, x: number, y: number, h: number, w: number) => void
  }

  export function install(app: App): void
}
````

I've only typed the parts that I'm using.  I use this for a dashboard designer - I'm adding widgets to the grid layout in a nice generic way and rendering them appropriately. 

I've modified this to work with vue 3:  https://github.com/jbaysolutions/vue-grid-layout/blob/master/website/docs/.vuepress/components/Example10DragFromOutside.vue

e.g:

````
      <div ref="dragArea" class="h-full w-full" @dragover.prevent>
        <grid-layout
          ref="layout"
          v-model:layout="dashboardLayout"
          :col-num="dashboardGridSettings.colNum"
          :row-height="dashboardGridSettings.rowHeight"
          :is-draggable="!showPreview"
          :is-resizable="!showPreview"
          :vertical-compact="true"
          :margin="[10, 10]"
        >
          <grid-item
            v-for="item in dashboardLayout"
            :ref="setGridItemRef"
            :key="item.i"
            :x="item.x"
            :y="item.y"
            :w="item.w"
            :h="item.h"
            :i="item.i"
            :min-h="item.minH"
            :min-w="item.minW"
            @resized="onResizedEvent"
          >
            <DashboardWidget :widget="item.widget" :is-designer-mode="!showPreview" />
          </grid-item>
        </grid-layout>
      </div>
````

**Comment by gmsa** [comment]
@MikesGlitch most of the PRs are incomplete, require review, documenting, etc. We've been super busy with actual paying client projects, which leaves little to no time to work on this.
If you're willing to contribute with good documentation or examples for the vue 3 branch, I will happily merge it.

**Comment by sokolinivan** [comment]
@MikesGlitch О! Thank you very much! I do customizable dynamic panels too :) Generally the view is collected from the data.
