### ISSUE TITLE
Vue3 + Vite ， Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by DYS1230** [jbaysolutions/vue-grid-layout#666]
Hi,

I use `vue-grid-layout@3.0.0-beta1` and `Vue3` with `Vite`, but I got error when excute `vite`  command:  

'runtime-core.cjs.js:6504 Uncaught TypeError: Cannot read properties of null (reading 'isCE')'

![pic](https://user-images.githubusercontent.com/13117927/163334427-12682e40-ff20-4bc8-9a02-7a5a3bea8923.png)

thx

**Comment by greegus** [comment]
According to [this answer](https://github.com/vuejs/core/issues/4344#issuecomment-899064501) this issue is caused by having Vue imported from multiple packages instead of using just one singleton. Persumably you are building your consumer application using Vite, so in that case addign following to the Vite's config should help.

```
resolve: {
  dedupe: [
    'vue'
  ]
},

**Comment by jiangdotgs** [comment]
解决了吗

**Comment by mandy222** [comment]
vue 运行版本跟依赖中 vue 版本不一致导致，通过这个链接解决了[https://blog.csdn.net/zhaoyapeng_/article/details/144451008](url)
