### ISSUE TITLE
Z-index problem

### ISSUE THREAD

**Issue by goalie7** [jbaysolutions/vue-grid-layout#71]
Hello again!

I'm trying to make some widgets for filtering data, but what I've found is that grid items in different rows are likely in different levels.

At first I thought it was something more related with charts because the following datepicker was showing behind but I can not click even in the visible parts (the one that are in red area):

![calendar_open](https://user-images.githubusercontent.com/7350351/27425728-b3e9fb38-5739-11e7-8bca-f8ddb76c332c.png)

![calendar_open_overlayed](https://user-images.githubusercontent.com/7350351/27425782-e1c19ffc-5739-11e7-99eb-a1f0f2d298e1.png)

Also, when having custom select components, the same happens:
![select_open](https://user-images.githubusercontent.com/7350351/27425977-7396939c-573a-11e7-97f1-2dd1f78bbc4e.png)

Have you faced something like this? I played with z-index but nothing worked

**UPDATED**
Here is a version without the chart:
![no_chart_overlay](https://user-images.githubusercontent.com/7350351/27426493-2b680d9c-573c-11e7-9d2d-7c94c9b3d725.png)

**Comment by gmsa** [comment]
The only place where z-index is used on vue-grid-layout is when dragging. 
I think the problems you have are between the charts and the datepicker.

**Comment by goalie7** [comment]
Thanks for your fast answer, with custom selects as (vue-select and vue-multiselect) this happens too, not with native btw. 

I thought the same, but check the update without chart is neither working, I will take a look further.

**Comment by itsarbit** [comment]
@goalie7 Did you finally solve this problem? How did you do that?

**Comment by thomashdk** [comment]
Do you find a fix for this? have the same issue?

**Comment by Cgarcilazo** [comment]
Hi, i've been having a problem putting a toolbar in front of any grid element, as you can see:
![image](https://user-images.githubusercontent.com/30292133/50596271-64220800-0e82-11e9-8a83-4f9e5790ca1a.png)
There is a problem using z-index and transform traslate3d(), as you can see here: 
https://stackoverflow.com/questions/20851452/z-index-is-canceled-by-setting-transformrotate
What i did to solve this problem is just deactivate css-transforms by doing `:use-css-transforms="false"` on the grid layout, so the z-index works now. I hope it helps someone.

**Comment by hiendv** [comment]
@Cgarcilazo Thank you. Your workaround works for me.
