### ISSUE TITLE
Get Item on change

### ISSUE THREAD

**Issue by tomtev** [jbaysolutions/vue-grid-layout#8]
Is there possible to return the item after dragging or resizing it?
F.ex @change="updateItem(item)" ?

**Comment by gmsa** [comment]
Sure, submit a working PR request and I'll be happy to merge

**Comment by ThePlastic** [comment]
I'm a noob with vue.js but for the same problem I simply created a computed property that monitor the layout and a watch method on the same computed property. The problem is that the watch method returns the entire items array, so I do a comparison with the previous layout (saved in a variable separately) and find the modified item. It is a little convoluted but performs perfectly its task

**Comment by gmsa** [comment]
Released on 2.1.0
